---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: production
  region: ap-northeast-2
  version: "1.21"

availabilityZones: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c", "ap-northeast-2d"]

managedNodeGroups:
  - name: nodegroup
    instanceType: m5.xlarge
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    volumeSize: 200
    ssh:
      allow: true
      publicKeyName: eks
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true

fargateProfiles:
  - name: fargate
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: fargate-dev
        labels:
          env: fargate-dev
          checks: passed
          
# To enable all of the control plane logs, uncomment below:
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

secretsEncryption:
  # for eksAdminRole, It is required to use only this role after the cluster creation
  # If not, it makes the authoriztion error
  keyARN: arn:aws:kms:ap-northeast-2:616278445611:key/aa374e4b-abce-4b68-96fc-b57f7f6dce25
  #keyARN: arn:aws:kms:ap-northeast-2:616278445611:key/8784ad52-4b5d-406e-843d-4c6d88bca2a8  # for ec2AdminRole
